# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/audio.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'grpc/audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10grpc/audio.proto\x1a\x1cgoogle/api/annotations.proto\"n\n\tAudioInfo\x12$\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\x0c.AudioFormatR\x06\x66ormat\x12\x1f\n\x0bsample_rate\x18\x02 \x01(\x05R\nsampleRate\x12\x1a\n\x08\x63hannels\x18\x03 \x01(\x05R\x08\x63hannels\"n\n\rRecordRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12)\n\x10\x64uration_seconds\x18\x02 \x01(\x05R\x0f\x64urationSeconds\x12\x1e\n\x04info\x18\x03 \x01(\x0b\x32\n.AudioInfoR\x04info\"\x85\x01\n\nAudioChunk\x12\x1d\n\naudio_data\x18\x01 \x01(\x0cR\taudioData\x12\x1c\n\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1a\n\x08sequence\x18\x03 \x01(\x05R\x08sequence\x12\x1e\n\x04info\x18\x04 \x01(\x0b\x32\n.AudioInfoR\x04info\"\xa3\x01\n\x0bPlayRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n\naudio_data\x18\x02 \x01(\x0cR\taudioData\x12$\n\x06\x66ormat\x18\x03 \x01(\x0e\x32\x0c.AudioFormatR\x06\x66ormat\x12\x1f\n\x0bsample_rate\x18\x04 \x01(\x05R\nsampleRate\x12\x1a\n\x08\x63hannels\x18\x05 \x01(\x05R\x08\x63hannels\"\"\n\x0cPlayResponse\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"\'\n\x11PropertiesRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"j\n\x12PropertiesResponse\x12\x38\n\x10supportedFormats\x18\x01 \x03(\x0e\x32\x0c.AudioFormatR\x10supportedFormats\x12\x1a\n\x08\x63hannels\x18\x02 \x01(\x05R\x08\x63hannels*F\n\x0b\x41udioFormat\x12\t\n\x05PCM16\x10\x00\x12\t\n\x05PCM32\x10\x01\x12\x0f\n\x0bPCM32_FLOAT\x10\x02\x12\x07\n\x03MP3\x10\x03\x12\x07\n\x03WAV\x10\x04\x32\xb1\x02\n\x0c\x41udioService\x12U\n\x04Play\x12\x0c.PlayRequest\x1a\r.PlayResponse\"0\x82\xd3\xe4\x93\x02*\"(/olivia/api/v1/service/audio/{name}/play\x12m\n\nProperties\x12\x12.PropertiesRequest\x1a\x13.PropertiesResponse\"6\x82\xd3\xe4\x93\x02\x30\"./olivia/api/v1/service/audio/{name}/properties\x12[\n\x06Record\x12\x0e.RecordRequest\x1a\x0b.AudioChunk\"2\x82\xd3\xe4\x93\x02,\"*/olivia/api/v1/service/audio/{name}/record0\x01\x42\tZ\x07./audiob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./audio'
  _globals['_AUDIOSERVICE'].methods_by_name['Play']._loaded_options = None
  _globals['_AUDIOSERVICE'].methods_by_name['Play']._serialized_options = b'\202\323\344\223\002*\"(/olivia/api/v1/service/audio/{name}/play'
  _globals['_AUDIOSERVICE'].methods_by_name['Properties']._loaded_options = None
  _globals['_AUDIOSERVICE'].methods_by_name['Properties']._serialized_options = b'\202\323\344\223\0020\"./olivia/api/v1/service/audio/{name}/properties'
  _globals['_AUDIOSERVICE'].methods_by_name['Record']._loaded_options = None
  _globals['_AUDIOSERVICE'].methods_by_name['Record']._serialized_options = b'\202\323\344\223\002,\"*/olivia/api/v1/service/audio/{name}/record'
  _globals['_AUDIOFORMAT']._serialized_start=761
  _globals['_AUDIOFORMAT']._serialized_end=831
  _globals['_AUDIOINFO']._serialized_start=50
  _globals['_AUDIOINFO']._serialized_end=160
  _globals['_RECORDREQUEST']._serialized_start=162
  _globals['_RECORDREQUEST']._serialized_end=272
  _globals['_AUDIOCHUNK']._serialized_start=275
  _globals['_AUDIOCHUNK']._serialized_end=408
  _globals['_PLAYREQUEST']._serialized_start=411
  _globals['_PLAYREQUEST']._serialized_end=574
  _globals['_PLAYRESPONSE']._serialized_start=576
  _globals['_PLAYRESPONSE']._serialized_end=610
  _globals['_PROPERTIESREQUEST']._serialized_start=612
  _globals['_PROPERTIESREQUEST']._serialized_end=651
  _globals['_PROPERTIESRESPONSE']._serialized_start=653
  _globals['_PROPERTIESRESPONSE']._serialized_end=759
  _globals['_AUDIOSERVICE']._serialized_start=834
  _globals['_AUDIOSERVICE']._serialized_end=1139
# @@protoc_insertion_point(module_scope)
